#!/bin/bash
set -e
shopt -s expand_aliases

. NIXUNITS/tests/json_status

ID="8643a4f5-c137-44ef-953e-e8b4aca9f924"
PRIVATE_HOST_IP4="10.0.1.1"
PRIVATE_IP4="10.0.2.2"
PRIVATE_HOST_IP6="fc00::x:y:z:1"
PRIVATE_IP6="fc00::a:b:c:2"
SERVICE_NAME="httpd"

# TODO : sandbox (Hydra ? )

DEBUG=0
WITH_OVS=false

while getopts "do" opt; do
  case $opt in
    d)
      DEBUG=1;;
    o)
      WITH_OVS=true;;
    *)
      echo "Invalid option"
      exit 1;;
  esac
done

test $DEBUG == 1 && set -ex

_err() {
  echo "$1"
  exit 1
}

alias _nixunits=NIXUNITS/bin/nixunits
_json() { _nixunits status $ID -o json; }
_jq() { _json | jq -r ".$1"; }

test "$(_jq declared_in_nixos)" == true && _err "Declared in NixOS"

# _nixunits delete $ID -frg > /dev/null
_nixunits delete $ID -fr > /dev/null


test "$(_json)" != "$STATUS_1_INITIAL" && _err "Invalid initial status : $(_json)"

nixunits create $ID -cn $SERVICE_NAME >/dev/null
test "$(_json)" != "$STATUS_1_CREATED" && _err "Invalid created status : $(_json)"

nixunits delete $ID -f
test "$(_json)" != "$STATUS_1_INITIAL" && _err "Invalid initial status : $(_json)"

_json

