#!/bin/bash

VERSION=25.11

STATUS_1_INITIAL=$(cat <<EOF
{
  "id": "8643a4f5-c137-44ef-953e-e8b4aca9f924",
  "os": "",
  "status": "initial",
  "version": "",
  "data_exist": false,
  "config_exist": false,
  "nix_same": false,
  "declared_in_nixos": false,
  "addresses": []
}
EOF
)

STATUS_1_CREATED=$(cat <<EOF
{
  "id": "8643a4f5-c137-44ef-953e-e8b4aca9f924",
  "os": "",
  "status": "created",
  "version": "",
  "data_exist": true,
  "config_exist": true,
  "nix_same": false,
  "declared_in_nixos": false,
  "addresses": []
}
EOF
)

STATUS_1_CREATED_NIX_SAME=$(cat <<EOF
{
  "id": "8643a4f5-c137-44ef-953e-e8b4aca9f924",
  "os": "",
  "status": "created",
  "version": "",
  "data_exist": true,
  "config_exist": true,
  "nix_same": true,
  "declared_in_nixos": false,
  "addresses": []
}
EOF
)

STATUS_1_STARTED=$(cat <<EOF
{
  "id": "8643a4f5-c137-44ef-953e-e8b4aca9f924",
  "os": "",
  "status": "started",
  "version": "",
  "data_exist": true,
  "config_exist": true,
  "nix_same": false,
  "declared_in_nixos": false
}
EOF
)

STATUS_1_STARTED_DETAILS=$(cat <<EOF
{
  "id": "8643a4f5-c137-44ef-953e-e8b4aca9f924",
  "os": "nixos",
  "status": "started",
  "version": "$VERSION",
  "data_exist": true,
  "config_exist": true,
  "nix_same": false,
  "declared_in_nixos": false
}
EOF
)

STATUS_1_INITIAL_WITH_DATA=$(cat <<EOF
{
  "id": "8643a4f5-c137-44ef-953e-e8b4aca9f924",
  "os": "",
  "status": "created",
  "version": "",
  "data_exist": true,
  "config_exist": false,
  "nix_same": false,
  "declared_in_nixos": false,
  "addresses": []
}
EOF
)
