#!/bin/bash
set -eo pipefail
trap 'echo -e "!!!!\n!!!! Error on $LINENO line : $BASH_COMMAND\n!!!!" >&2' ERR

# shellcheck disable=SC1091
. _NIXUNITS_PATH_SED_/bin/common.sh

export PATH=$PATH:_OPENVSWITCH_PATH_SED_/bin

interface_ovs_create() {
  log_msg "Create OVS interface - $INTERFACE - "
  if ! interface_exists "$INTERFACE"; then
    if ovs_port_exists "$INTERFACE"; then
      ovs_port_del "$INTERFACE"
    fi
    ovs_port_add "$INTERFACE"
  fi
}

###############################################################################
# Main
###############################################################################

log_block_msg "### nixunits START PRE"

for iface in $(interfaces_list); do
  interface_env "$iface"
  if [ -n "$OVS_BRIDGE" ]; then
    interface_ovs_create
  fi
done

log_msg "### nixunits END PRE ###"