#!/bin/bash
set -eo pipefail

. _NIXUNITS_PATH_SED_/bin/common.sh

log_block_msg "### nixunits STOP PRE"

NS_PID=$(host_exec "ps --ppid $MAINPID -o pid h")

UNWANTED=$(pid_in_ns_not_in_container "$NS_PID")

for p in $UNWANTED; do
  log_msg "Kill pid $p"
  [ -d "/proc/$p" ] && kill "$p" 2>/dev/null
done
sleep 1
UNWANTED=$(for p in $UNWANTED; do [ -d "/proc/$p" ] && echo "$p"; done)
[ -z "$UNWANTED" ] || sleep 6

UNWANTED=$(pid_in_ns_not_in_container "$NS_PID")
for p in $UNWANTED; do
  log_msg "Kill -9 pid $p"
  [ -d "/proc/$p" ] && kill -9 "$p" 2>/dev/null
done

log_block_msg "### nixunits STOP PRE"
