#!/bin/bash
set -eo pipefail
trap 'echo -e "!!!!\n!!!! Error on $LINENO line : $BASH_COMMAND\n!!!!" >&2' ERR

# shellcheck disable=SC1091
. _NIXUNITS_PATH_SED_/bin/common.sh

export PATH=$PATH:_OPENVSWITCH_PATH_SED_/bin

log_msg() {
  echo "$1" >&2
}

log_block_msg() {
  log_msg "########################################"
  log_msg "# $1"
  log_msg "########################################"
}

interface_ovs_create() {
  log_msg "Create OVS interface - $INTERFACE - "
  if ! interface_exists "$INTERFACE"; then
    if ovs_port_exists "$INTERFACE"; then
      ovs_port_del "$INTERFACE"
    fi
    ovs_port_add "$INTERFACE"
  fi
}

interface_exists() {
  ip link show "$1" &>/dev/null || return 1
}

ovs_port_exists() {
  ovs-vsctl --if-exists get Interface "$1" name &>/dev/null
}

ovs_port_del() {
  ovs-vsctl --if-exists del-port "$OVS_BRIDGE" "$1"
}

ovs_port_add() {
  if [[ -n "$OVS_VLAN" ]]; then
    ovs-vsctl add-port "$OVS_BRIDGE" "$1" tag="$OVS_VLAN" -- set interface "$1" type=internal
  else
    ovs-vsctl add-port "$OVS_BRIDGE" "$1" -- set interface "$1" type=internal
  fi
}


###############################################################################
# Main
###############################################################################

log_block_msg "### nixunits START PRE"

for iface in $(interfaces_list); do
  interface_env "$iface"
  if [ -n "$OVS_BRIDGE" ]; then
    interface_ovs_create
  fi
done

log_msg "### nixunits END PRE ###"