#!/bin/bash
set -eo pipefail
trap 'echo -e "!!!!\n!!!! Error on $LINENO line : $BASH_COMMAND\n!!!!" >&2' ERR

# shellcheck disable=SC1091
. _NIXUNITS_PATH_SED_/bin/common.sh

NFT=_NFT_BIN_SED_
SH="$SYSTEM_PATH/sw/bin/sh"

container_exec() {
  log_msg "[ Container ($NS_PID) ] netns exec $1"
  nsenter --target "$NS_PID" --uts --ipc --net --pid -- /bin/sh -c "$1"
}

interface_ns_set() {
  container_exec "ip link set dev $INTERFACE down"
  container_exec "ip addr flush dev $INTERFACE"
  container_exec "ip route flush dev $INTERFACE"
  container_exec "ip -6 route flush dev $INTERFACE"
  container_exec "ip link set dev $INTERFACE up"
  if [ -n "$IP4" ]; then
    container_exec "ip -4 a replace $IP4 dev $INTERFACE"
  fi
  if [ -n "$IP6" ]; then
    container_exec "ip -6 a replace $IP6 dev $INTERFACE"
  fi

  if [ -n "$HOST_INTERFACE" ]; then
    if [ -n "$HOST_IP4" ]; then
      if [ "${HOST_IP4#*/}" = "31" ]; then
        container_exec "ip -4 route replace ${HOST_IP4%/*} dev $INTERFACE"
      else
        container_exec "ip -4 route replace $HOST_IP4 dev $INTERFACE"
      fi
    fi
    if [ -n "$HOST_IP6" ]; then
      if [ "${HOST_IP6#*/}" = "127" ]; then
        container_exec "ip -6 route replace ${HOST_IP6%/*} dev $INTERFACE"
      else
        container_exec "ip -6 route replace $HOST_IP6 dev $INTERFACE"
      fi
    fi
  fi

  if [ -n "$MV" ]; then
    container_exec "ip link set dev $MV up"
    if [ -n "$MV_IP4" ]; then
      container_exec "ip -4 a replace $MV_IP4 dev $MV"
    fi
    if [ -n "$MV_IP6" ]; then
      container_exec "ip -6 a replace $MV_IP6 dev $MV"
    fi
  fi
}

interface_host_set() {
  if [ -n "$HOST_INTERFACE" ]; then
    log_msg "### Configure interface host - ${HOST_INTERFACE} -"

    host_exec "ip link set dev $HOST_INTERFACE down"
    host_exec "ip addr flush dev $HOST_INTERFACE"
    host_exec "ip route flush dev $HOST_INTERFACE"
    host_exec "ip -6 route flush dev $HOST_INTERFACE"
    host_exec "ip link set dev $HOST_INTERFACE up"
    if [ "$HOST_IP4" ]; then
      host_exec "ip -4 a add $HOST_IP4 dev $HOST_INTERFACE"
    fi
    if [ "$HOST_IP6" ]; then
      host_exec "ip -6 a add $HOST_IP6 dev $HOST_INTERFACE"
    fi
    if [ -n "$IP4" ]; then
      if [ "${IP4#*/}" = "31" ]; then
        host_exec "ip -4 route add ${IP4%/*} dev $HOST_INTERFACE"
      else
        host_exec "ip -4 route add $IP4 dev $HOST_INTERFACE"
      fi
    fi
    if [ -n "$IP6" ]; then
      if [ "${IP6#*/}" = "127" ]; then
        host_exec "ip -6 route add ${IP6%/*} dev $HOST_INTERFACE"
      else
        host_exec "ip -6 route add $IP6 dev $HOST_INTERFACE"
      fi
    fi
  fi
}

context_set() {
  if { { [ -n "$IP4" ] && [ -n "$HOST_IP4" ]; } || { [ -n "$IP6" ] && [ -n "$HOST_IP6" ]; }; }; then
    if_infos=$(container_exec "ip -j link" | jq '.[] | select(.link_index != null)')
    host_interface_id=$(echo "$if_infos" | jq '.link_index')
    INTERFACE=$(echo "$if_infos" | jq -r '.ifname')
    HOST_INTERFACE=$(ip -j link | jq -r ".[] | select(.ifindex == $host_interface_id) | .ifname")
  fi
}

###############################################################################
# Main
###############################################################################

_ROOT_=/var/lib/nixunits/containers/$NAME/root

log_block_msg "### nixunits START NETWORK CONFIG"

NS_PID=$(pid_leader "$NAME")

if [ -n "$NFT_FILE" ]; then
  container_exec "$NFT -f ${_ROOT_}$NFT_FILE"
fi

if [ -z "$(interfaces_list)" ]
then
  log_block_msg "### Private network without IP (exit)"
else
  for iface in $(interfaces_list); do
    interface_env "$iface"
    context_set
    log_msg "### Configure interface container - ${INTERFACE} -"
    interface_ns_set
    interface_host_set
  done
fi

if [ -n "$IP4ROUTE" ]; then
  container_exec "ip -4 route add default via $IP4ROUTE"
fi

if [ -n "$IP6ROUTE" ]; then
  if echo "$IP6ROUTE" | grep -q "^fe80"; then
    iface_count=$(interfaces_list | wc -w)
    if [ "$iface_count" -eq 1 ]; then
      iface=$(interfaces_list)
      container_exec "ip -6 route add default via $IP6ROUTE dev $iface"
    else
      log_msg "### IPv6 route fe80 detected but multiple interfaces found"
      exit 1
    fi
  else
    container_exec "ip -6 route add default via $IP6ROUTE"
  fi
fi

nsenter --target "$NS_PID" --all -- "$SH" -c "> /run/net-ready"

log_msg "### nixunits END NETWORK CONFIG ###"