#!/bin/bash
set -eo pipefail
trap 'echo -e "!!!!\n!!!! Error on $LINENO line : $BASH_COMMAND\n!!!!" >&2' ERR

ID=$1
# shellcheck disable=SC1091
. _NIXUNITS_PATH_SED_/bin/common.sh

export PATH=$PATH:_OPENVSWITCH_PATH_SED_/bin
UNIT_DIR=$(unit_dir "$ID")
UID_ROOT=$(uid_root "$ID")
MAX_UID=$(( UID_ROOT + 65535 ))

interface_check() {
  interface_env "$1"
  log_msg "Create OVS interface - $INTERFACE - "
  if ! interface_exists "$INTERFACE"; then
    if ovs_port_exists "$INTERFACE" true; then
      if [ -n "$OVS_BRIDGE" ]; then
        ovs_port_del "$INTERFACE"
      fi
    fi
    if [ -n "$OVS_BRIDGE" ]; then
      ovs_port_add "$INTERFACE"
    fi
  fi
}

owner_fix() {
    local dst="$1" src="$2"
    local current="/"
    local IFS='/'
    local uid
    local target

    read -ra parts <<< "$dst"
    for i in "${!parts[@]}"; do
        [[ -z "${parts[$i]}" ]] && continue
        current="$current${parts[$i]}"

        local target="$UNIT_DIR/root$current"
        if [[ $i -eq $((${#parts[@]} - 1)) ]]; then
          target="$src"
        fi
        uid=$(stat -c '%u' "$target" 2>/dev/null || echo -1)
        if (( uid < UID_ROOT || uid > MAX_UID )); then
            log_msg "chown $UID_ROOT:$UID_ROOT $target"
            mkdir -p "$target"
            chown "$UID_ROOT":"$UID_ROOT" "$target"
        fi

        current="$current/"
    done
}

###############################################################################
# Main
###############################################################################

log_block_msg "### nixunits START PRE"

for iface in $(interfaces_list); do
  interface_check "$iface"
done

for arg_ in $NSPAWN_ARGS; do
    case "$arg_" in
        --bind=*)
            val="${arg_#--bind=}"

            if [[ "$val" == *:* ]]; then
                src="${val%%:*}"
                dst="${val#*:}"
            else
                src="$val"
                dst="$val"
            fi

            owner_fix "$dst" "$src"
            ;;
    esac
done

log_msg "### nixunits END PRE ###"