#!/bin/bash
set -eo pipefail
trap 'echo -e "!!!!\n!!!! Error on $LINENO line : $BASH_COMMAND\n!!!!" >&2' ERR

# shellcheck disable=SC1091
. NIXUNITS/bin/common.sh

log_msg() {
  echo "$1" >&2
}

log_block_msg() {
  log_msg "########################################"
  log_msg "# $1"
  log_msg "########################################"
}

###############################################################################
# Main
###############################################################################

log_block_msg "### nixunits START PRE"

log_msg "### nixunits END PRE ###"