#!/bin/sh
set -e

. NIXUNITS/bin/common.sh

host_eval() {
  echo "Host eval $1" >> "$LOG"
  /bin/sh -c "$1" 2>> "$LOG"
}

nsenter_eval() {
  echo "NS eval $1" >> "$LOG"
  nsenter --target $NS_PID --mount --uts --ipc --net --pid -- /bin/sh -c "$1" 2>> "$LOG"
}

LOG=$(log "$NAME")

echo "[$(date)] - - - START POST - - - $NAME" >> "$LOG"

NS_PID=$(host_eval "ps --ppid $MAINPID -o pid h")

if [ -z "$INTERFACE" ] && { { [ -n "$IP4" ] && [ -n "$HOST_IP4" ]; } || { [ -n "$IP6" ] && [ -n "$HOST_IP6" ]; }; }
then
  if_infos=$(nsenter_eval "ip -j link" | jq '.[] | select(.ifname != "lo")')
  host_interface_id=$(echo "$if_infos" | jq '.link_index')
  INTERFACE=$(echo "$if_infos" | jq -r '.ifname')
  HOST_INTERFACE=$(ip -j link | jq -r ".[] | select(.ifindex == $host_interface_id) | .ifname")
else
  exit 0
fi

echo -e "\n- - Unit config - -" >> "$LOG"

test -n "$IP4" && nsenter_eval "ip -4 a add $IP4 dev $INTERFACE"
test -n "$IP6" && nsenter_eval "ip -6 a add $IP6 dev $INTERFACE"
test -n "$INTERFACE" && nsenter_eval "ip link set dev $INTERFACE up"

if test -n "$HOST_INTERFACE"
then
  if test -n "$HOST_IP4"
  then
    nsenter_eval "ip -4 route add ${HOST_IP4} dev $INTERFACE"
    nsenter_eval "ip -4 route default via ${HOST_IP4}"
  fi
  if test -n "$HOST_IP6"
  then
     nsenter_eval "ip -6 route add ${HOST_IP6} dev $INTERFACE"
     nsenter_eval "ip -6 route default via ${HOST_IP6}"
  fi
else
  test -n "$IP4_ROUTE" && nsenter_eval "ip -4 route add default via $IP4_ROUTE dev $INTERFACE"
  test -n "$IP6_ROUTE" && nsenter_eval "ip -6 route add default via $IP6_ROUTE dev $INTERFACE"
fi

echo -e "\n- - Host config - -" >> "$LOG"

if test -n "$HOST_INTERFACE"
then
  test -n "$HOST_IP4" && host_eval "ip -4 a add $HOST_IP4 dev $HOST_INTERFACE"
  test -n "$HOST_IP6" && host_eval "ip -6 a add $HOST_IP6 dev $HOST_INTERFACE"
  host_eval "ip link set dev $HOST_INTERFACE up"
  test -n "$IP4" && host_eval "ip -4 route add $IP4 dev $HOST_INTERFACE"
  test -n "$IP6" && host_eval "ip -6 route add $IP6 dev $HOST_INTERFACE"
fi

_resolv=$(cat /etc/resolv.conf)
nsenter_eval "echo \"$_resolv\" > /etc/resolv.conf"

echo "[$(date)] - - - END POST - - - $NAME" >> "$LOG"
